- job:
    name: teuthology-pull-requests 
    node: trusty && amd64 && small
    project-type: freestyle
    defaults: global
    concurrent: true
    display-name: 'Teuthology: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/teuthology/
    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - ktdreyer
            - trhoden
            - zmc
            - andrewschoen
            - dmick
          org-list:
            - ceph
          white-list:
            - jcsp
            - gregsfortytwo
            - GregMeno
            - dzafman
            - dillaman
            - dachary
            - liewegas
            - idryomov
            - vasukulkarni
            - ivotron
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/teuthology.git
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw ../../setup/setup
      - shell:
          !include-raw ../../build/build

    publishers:
      - github-notifier
